// Code generated by counterfeiter. DO NOT EDIT.
package slsafakes

import (
	"context"
	"sync"

	"github.com/policylabs/attestation"
	"github.com/slsa-framework/verifier/pkg/slsa"
	"github.com/slsa-framework/verifier/pkg/slsa/builders"
	"github.com/slsa-framework/verifier/pkg/slsa/controls"
	"github.com/slsa-framework/verifier/pkg/subject"
)

type FakeVerifierImplementation struct {
	CheckBuilderStub        func(context.Context, *slsa.VerificationOptions, *builders.Registry, attestation.Statement) (*slsa.ControlResult, error)
	checkBuilderMutex       sync.RWMutex
	checkBuilderArgsForCall []struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 *builders.Registry
		arg4 attestation.Statement
	}
	checkBuilderReturns struct {
		result1 *slsa.ControlResult
		result2 error
	}
	checkBuilderReturnsOnCall map[int]struct {
		result1 *slsa.ControlResult
		result2 error
	}
	CheckIdentitiesStub        func(context.Context, *slsa.VerificationOptions, attestation.Statement) error
	checkIdentitiesMutex       sync.RWMutex
	checkIdentitiesArgsForCall []struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 attestation.Statement
	}
	checkIdentitiesReturns struct {
		result1 error
	}
	checkIdentitiesReturnsOnCall map[int]struct {
		result1 error
	}
	CheckSubjectsStub        func(context.Context, *slsa.VerificationOptions, attestation.Statement) ([]subject.Match, error)
	checkSubjectsMutex       sync.RWMutex
	checkSubjectsArgsForCall []struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 attestation.Statement
	}
	checkSubjectsReturns struct {
		result1 []subject.Match
		result2 error
	}
	checkSubjectsReturnsOnCall map[int]struct {
		result1 []subject.Match
		result2 error
	}
	ComputeResultStub        func(*slsa.VerificationOptions, []*slsa.ControlResult, []*slsa.ControlResult, []*slsa.ControlResult) (*slsa.Result, error)
	computeResultMutex       sync.RWMutex
	computeResultArgsForCall []struct {
		arg1 *slsa.VerificationOptions
		arg2 []*slsa.ControlResult
		arg3 []*slsa.ControlResult
		arg4 []*slsa.ControlResult
	}
	computeResultReturns struct {
		result1 *slsa.Result
		result2 error
	}
	computeResultReturnsOnCall map[int]struct {
		result1 *slsa.Result
		result2 error
	}
	ResolveCategoryStub        func(*slsa.VerificationOptions, *controls.Catalog, attestation.Statement) (controls.Category, error)
	resolveCategoryMutex       sync.RWMutex
	resolveCategoryArgsForCall []struct {
		arg1 *slsa.VerificationOptions
		arg2 *controls.Catalog
		arg3 attestation.Statement
	}
	resolveCategoryReturns struct {
		result1 controls.Category
		result2 error
	}
	resolveCategoryReturnsOnCall map[int]struct {
		result1 controls.Category
		result2 error
	}
	RunControlsStub        func(context.Context, *slsa.VerificationOptions, []*controls.Control, attestation.Statement) ([]*slsa.ControlResult, error)
	runControlsMutex       sync.RWMutex
	runControlsArgsForCall []struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 []*controls.Control
		arg4 attestation.Statement
	}
	runControlsReturns struct {
		result1 []*slsa.ControlResult
		result2 error
	}
	runControlsReturnsOnCall map[int]struct {
		result1 []*slsa.ControlResult
		result2 error
	}
	SelectBuildTypeControlsStub        func(*slsa.VerificationOptions, *controls.Catalog, attestation.Statement) []*controls.Control
	selectBuildTypeControlsMutex       sync.RWMutex
	selectBuildTypeControlsArgsForCall []struct {
		arg1 *slsa.VerificationOptions
		arg2 *controls.Catalog
		arg3 attestation.Statement
	}
	selectBuildTypeControlsReturns struct {
		result1 []*controls.Control
	}
	selectBuildTypeControlsReturnsOnCall map[int]struct {
		result1 []*controls.Control
	}
	SelectCoreControlsStub        func(*slsa.VerificationOptions, *controls.Catalog, controls.Category) []*controls.Control
	selectCoreControlsMutex       sync.RWMutex
	selectCoreControlsArgsForCall []struct {
		arg1 *slsa.VerificationOptions
		arg2 *controls.Catalog
		arg3 controls.Category
	}
	selectCoreControlsReturns struct {
		result1 []*controls.Control
	}
	selectCoreControlsReturnsOnCall map[int]struct {
		result1 []*controls.Control
	}
	SelectUserControlsStub        func(*slsa.VerificationOptions) []*controls.Control
	selectUserControlsMutex       sync.RWMutex
	selectUserControlsArgsForCall []struct {
		arg1 *slsa.VerificationOptions
	}
	selectUserControlsReturns struct {
		result1 []*controls.Control
	}
	selectUserControlsReturnsOnCall map[int]struct {
		result1 []*controls.Control
	}
	VerifySignaturesStub        func(context.Context, *slsa.VerificationOptions, attestation.Statement) error
	verifySignaturesMutex       sync.RWMutex
	verifySignaturesArgsForCall []struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 attestation.Statement
	}
	verifySignaturesReturns struct {
		result1 error
	}
	verifySignaturesReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVerifierImplementation) CheckBuilder(arg1 context.Context, arg2 *slsa.VerificationOptions, arg3 *builders.Registry, arg4 attestation.Statement) (*slsa.ControlResult, error) {
	fake.checkBuilderMutex.Lock()
	ret, specificReturn := fake.checkBuilderReturnsOnCall[len(fake.checkBuilderArgsForCall)]
	fake.checkBuilderArgsForCall = append(fake.checkBuilderArgsForCall, struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 *builders.Registry
		arg4 attestation.Statement
	}{arg1, arg2, arg3, arg4})
	stub := fake.CheckBuilderStub
	fakeReturns := fake.checkBuilderReturns
	fake.recordInvocation("CheckBuilder", []interface{}{arg1, arg2, arg3, arg4})
	fake.checkBuilderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVerifierImplementation) CheckBuilderCallCount() int {
	fake.checkBuilderMutex.RLock()
	defer fake.checkBuilderMutex.RUnlock()
	return len(fake.checkBuilderArgsForCall)
}

func (fake *FakeVerifierImplementation) CheckBuilderCalls(stub func(context.Context, *slsa.VerificationOptions, *builders.Registry, attestation.Statement) (*slsa.ControlResult, error)) {
	fake.checkBuilderMutex.Lock()
	defer fake.checkBuilderMutex.Unlock()
	fake.CheckBuilderStub = stub
}

func (fake *FakeVerifierImplementation) CheckBuilderArgsForCall(i int) (context.Context, *slsa.VerificationOptions, *builders.Registry, attestation.Statement) {
	fake.checkBuilderMutex.RLock()
	defer fake.checkBuilderMutex.RUnlock()
	argsForCall := fake.checkBuilderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeVerifierImplementation) CheckBuilderReturns(result1 *slsa.ControlResult, result2 error) {
	fake.checkBuilderMutex.Lock()
	defer fake.checkBuilderMutex.Unlock()
	fake.CheckBuilderStub = nil
	fake.checkBuilderReturns = struct {
		result1 *slsa.ControlResult
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) CheckBuilderReturnsOnCall(i int, result1 *slsa.ControlResult, result2 error) {
	fake.checkBuilderMutex.Lock()
	defer fake.checkBuilderMutex.Unlock()
	fake.CheckBuilderStub = nil
	if fake.checkBuilderReturnsOnCall == nil {
		fake.checkBuilderReturnsOnCall = make(map[int]struct {
			result1 *slsa.ControlResult
			result2 error
		})
	}
	fake.checkBuilderReturnsOnCall[i] = struct {
		result1 *slsa.ControlResult
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) CheckIdentities(arg1 context.Context, arg2 *slsa.VerificationOptions, arg3 attestation.Statement) error {
	fake.checkIdentitiesMutex.Lock()
	ret, specificReturn := fake.checkIdentitiesReturnsOnCall[len(fake.checkIdentitiesArgsForCall)]
	fake.checkIdentitiesArgsForCall = append(fake.checkIdentitiesArgsForCall, struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 attestation.Statement
	}{arg1, arg2, arg3})
	stub := fake.CheckIdentitiesStub
	fakeReturns := fake.checkIdentitiesReturns
	fake.recordInvocation("CheckIdentities", []interface{}{arg1, arg2, arg3})
	fake.checkIdentitiesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVerifierImplementation) CheckIdentitiesCallCount() int {
	fake.checkIdentitiesMutex.RLock()
	defer fake.checkIdentitiesMutex.RUnlock()
	return len(fake.checkIdentitiesArgsForCall)
}

func (fake *FakeVerifierImplementation) CheckIdentitiesCalls(stub func(context.Context, *slsa.VerificationOptions, attestation.Statement) error) {
	fake.checkIdentitiesMutex.Lock()
	defer fake.checkIdentitiesMutex.Unlock()
	fake.CheckIdentitiesStub = stub
}

func (fake *FakeVerifierImplementation) CheckIdentitiesArgsForCall(i int) (context.Context, *slsa.VerificationOptions, attestation.Statement) {
	fake.checkIdentitiesMutex.RLock()
	defer fake.checkIdentitiesMutex.RUnlock()
	argsForCall := fake.checkIdentitiesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVerifierImplementation) CheckIdentitiesReturns(result1 error) {
	fake.checkIdentitiesMutex.Lock()
	defer fake.checkIdentitiesMutex.Unlock()
	fake.CheckIdentitiesStub = nil
	fake.checkIdentitiesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVerifierImplementation) CheckIdentitiesReturnsOnCall(i int, result1 error) {
	fake.checkIdentitiesMutex.Lock()
	defer fake.checkIdentitiesMutex.Unlock()
	fake.CheckIdentitiesStub = nil
	if fake.checkIdentitiesReturnsOnCall == nil {
		fake.checkIdentitiesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkIdentitiesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVerifierImplementation) CheckSubjects(arg1 context.Context, arg2 *slsa.VerificationOptions, arg3 attestation.Statement) ([]subject.Match, error) {
	fake.checkSubjectsMutex.Lock()
	ret, specificReturn := fake.checkSubjectsReturnsOnCall[len(fake.checkSubjectsArgsForCall)]
	fake.checkSubjectsArgsForCall = append(fake.checkSubjectsArgsForCall, struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 attestation.Statement
	}{arg1, arg2, arg3})
	stub := fake.CheckSubjectsStub
	fakeReturns := fake.checkSubjectsReturns
	fake.recordInvocation("CheckSubjects", []interface{}{arg1, arg2, arg3})
	fake.checkSubjectsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVerifierImplementation) CheckSubjectsCallCount() int {
	fake.checkSubjectsMutex.RLock()
	defer fake.checkSubjectsMutex.RUnlock()
	return len(fake.checkSubjectsArgsForCall)
}

func (fake *FakeVerifierImplementation) CheckSubjectsCalls(stub func(context.Context, *slsa.VerificationOptions, attestation.Statement) ([]subject.Match, error)) {
	fake.checkSubjectsMutex.Lock()
	defer fake.checkSubjectsMutex.Unlock()
	fake.CheckSubjectsStub = stub
}

func (fake *FakeVerifierImplementation) CheckSubjectsArgsForCall(i int) (context.Context, *slsa.VerificationOptions, attestation.Statement) {
	fake.checkSubjectsMutex.RLock()
	defer fake.checkSubjectsMutex.RUnlock()
	argsForCall := fake.checkSubjectsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVerifierImplementation) CheckSubjectsReturns(result1 []subject.Match, result2 error) {
	fake.checkSubjectsMutex.Lock()
	defer fake.checkSubjectsMutex.Unlock()
	fake.CheckSubjectsStub = nil
	fake.checkSubjectsReturns = struct {
		result1 []subject.Match
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) CheckSubjectsReturnsOnCall(i int, result1 []subject.Match, result2 error) {
	fake.checkSubjectsMutex.Lock()
	defer fake.checkSubjectsMutex.Unlock()
	fake.CheckSubjectsStub = nil
	if fake.checkSubjectsReturnsOnCall == nil {
		fake.checkSubjectsReturnsOnCall = make(map[int]struct {
			result1 []subject.Match
			result2 error
		})
	}
	fake.checkSubjectsReturnsOnCall[i] = struct {
		result1 []subject.Match
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) ComputeResult(arg1 *slsa.VerificationOptions, arg2 []*slsa.ControlResult, arg3 []*slsa.ControlResult, arg4 []*slsa.ControlResult) (*slsa.Result, error) {
	var arg2Copy []*slsa.ControlResult
	if arg2 != nil {
		arg2Copy = make([]*slsa.ControlResult, len(arg2))
		copy(arg2Copy, arg2)
	}
	var arg3Copy []*slsa.ControlResult
	if arg3 != nil {
		arg3Copy = make([]*slsa.ControlResult, len(arg3))
		copy(arg3Copy, arg3)
	}
	var arg4Copy []*slsa.ControlResult
	if arg4 != nil {
		arg4Copy = make([]*slsa.ControlResult, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.computeResultMutex.Lock()
	ret, specificReturn := fake.computeResultReturnsOnCall[len(fake.computeResultArgsForCall)]
	fake.computeResultArgsForCall = append(fake.computeResultArgsForCall, struct {
		arg1 *slsa.VerificationOptions
		arg2 []*slsa.ControlResult
		arg3 []*slsa.ControlResult
		arg4 []*slsa.ControlResult
	}{arg1, arg2Copy, arg3Copy, arg4Copy})
	stub := fake.ComputeResultStub
	fakeReturns := fake.computeResultReturns
	fake.recordInvocation("ComputeResult", []interface{}{arg1, arg2Copy, arg3Copy, arg4Copy})
	fake.computeResultMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVerifierImplementation) ComputeResultCallCount() int {
	fake.computeResultMutex.RLock()
	defer fake.computeResultMutex.RUnlock()
	return len(fake.computeResultArgsForCall)
}

func (fake *FakeVerifierImplementation) ComputeResultCalls(stub func(*slsa.VerificationOptions, []*slsa.ControlResult, []*slsa.ControlResult, []*slsa.ControlResult) (*slsa.Result, error)) {
	fake.computeResultMutex.Lock()
	defer fake.computeResultMutex.Unlock()
	fake.ComputeResultStub = stub
}

func (fake *FakeVerifierImplementation) ComputeResultArgsForCall(i int) (*slsa.VerificationOptions, []*slsa.ControlResult, []*slsa.ControlResult, []*slsa.ControlResult) {
	fake.computeResultMutex.RLock()
	defer fake.computeResultMutex.RUnlock()
	argsForCall := fake.computeResultArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeVerifierImplementation) ComputeResultReturns(result1 *slsa.Result, result2 error) {
	fake.computeResultMutex.Lock()
	defer fake.computeResultMutex.Unlock()
	fake.ComputeResultStub = nil
	fake.computeResultReturns = struct {
		result1 *slsa.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) ComputeResultReturnsOnCall(i int, result1 *slsa.Result, result2 error) {
	fake.computeResultMutex.Lock()
	defer fake.computeResultMutex.Unlock()
	fake.ComputeResultStub = nil
	if fake.computeResultReturnsOnCall == nil {
		fake.computeResultReturnsOnCall = make(map[int]struct {
			result1 *slsa.Result
			result2 error
		})
	}
	fake.computeResultReturnsOnCall[i] = struct {
		result1 *slsa.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) ResolveCategory(arg1 *slsa.VerificationOptions, arg2 *controls.Catalog, arg3 attestation.Statement) (controls.Category, error) {
	fake.resolveCategoryMutex.Lock()
	ret, specificReturn := fake.resolveCategoryReturnsOnCall[len(fake.resolveCategoryArgsForCall)]
	fake.resolveCategoryArgsForCall = append(fake.resolveCategoryArgsForCall, struct {
		arg1 *slsa.VerificationOptions
		arg2 *controls.Catalog
		arg3 attestation.Statement
	}{arg1, arg2, arg3})
	stub := fake.ResolveCategoryStub
	fakeReturns := fake.resolveCategoryReturns
	fake.recordInvocation("ResolveCategory", []interface{}{arg1, arg2, arg3})
	fake.resolveCategoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVerifierImplementation) ResolveCategoryCallCount() int {
	fake.resolveCategoryMutex.RLock()
	defer fake.resolveCategoryMutex.RUnlock()
	return len(fake.resolveCategoryArgsForCall)
}

func (fake *FakeVerifierImplementation) ResolveCategoryCalls(stub func(*slsa.VerificationOptions, *controls.Catalog, attestation.Statement) (controls.Category, error)) {
	fake.resolveCategoryMutex.Lock()
	defer fake.resolveCategoryMutex.Unlock()
	fake.ResolveCategoryStub = stub
}

func (fake *FakeVerifierImplementation) ResolveCategoryArgsForCall(i int) (*slsa.VerificationOptions, *controls.Catalog, attestation.Statement) {
	fake.resolveCategoryMutex.RLock()
	defer fake.resolveCategoryMutex.RUnlock()
	argsForCall := fake.resolveCategoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVerifierImplementation) ResolveCategoryReturns(result1 controls.Category, result2 error) {
	fake.resolveCategoryMutex.Lock()
	defer fake.resolveCategoryMutex.Unlock()
	fake.ResolveCategoryStub = nil
	fake.resolveCategoryReturns = struct {
		result1 controls.Category
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) ResolveCategoryReturnsOnCall(i int, result1 controls.Category, result2 error) {
	fake.resolveCategoryMutex.Lock()
	defer fake.resolveCategoryMutex.Unlock()
	fake.ResolveCategoryStub = nil
	if fake.resolveCategoryReturnsOnCall == nil {
		fake.resolveCategoryReturnsOnCall = make(map[int]struct {
			result1 controls.Category
			result2 error
		})
	}
	fake.resolveCategoryReturnsOnCall[i] = struct {
		result1 controls.Category
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) RunControls(arg1 context.Context, arg2 *slsa.VerificationOptions, arg3 []*controls.Control, arg4 attestation.Statement) ([]*slsa.ControlResult, error) {
	var arg3Copy []*controls.Control
	if arg3 != nil {
		arg3Copy = make([]*controls.Control, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.runControlsMutex.Lock()
	ret, specificReturn := fake.runControlsReturnsOnCall[len(fake.runControlsArgsForCall)]
	fake.runControlsArgsForCall = append(fake.runControlsArgsForCall, struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 []*controls.Control
		arg4 attestation.Statement
	}{arg1, arg2, arg3Copy, arg4})
	stub := fake.RunControlsStub
	fakeReturns := fake.runControlsReturns
	fake.recordInvocation("RunControls", []interface{}{arg1, arg2, arg3Copy, arg4})
	fake.runControlsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVerifierImplementation) RunControlsCallCount() int {
	fake.runControlsMutex.RLock()
	defer fake.runControlsMutex.RUnlock()
	return len(fake.runControlsArgsForCall)
}

func (fake *FakeVerifierImplementation) RunControlsCalls(stub func(context.Context, *slsa.VerificationOptions, []*controls.Control, attestation.Statement) ([]*slsa.ControlResult, error)) {
	fake.runControlsMutex.Lock()
	defer fake.runControlsMutex.Unlock()
	fake.RunControlsStub = stub
}

func (fake *FakeVerifierImplementation) RunControlsArgsForCall(i int) (context.Context, *slsa.VerificationOptions, []*controls.Control, attestation.Statement) {
	fake.runControlsMutex.RLock()
	defer fake.runControlsMutex.RUnlock()
	argsForCall := fake.runControlsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeVerifierImplementation) RunControlsReturns(result1 []*slsa.ControlResult, result2 error) {
	fake.runControlsMutex.Lock()
	defer fake.runControlsMutex.Unlock()
	fake.RunControlsStub = nil
	fake.runControlsReturns = struct {
		result1 []*slsa.ControlResult
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) RunControlsReturnsOnCall(i int, result1 []*slsa.ControlResult, result2 error) {
	fake.runControlsMutex.Lock()
	defer fake.runControlsMutex.Unlock()
	fake.RunControlsStub = nil
	if fake.runControlsReturnsOnCall == nil {
		fake.runControlsReturnsOnCall = make(map[int]struct {
			result1 []*slsa.ControlResult
			result2 error
		})
	}
	fake.runControlsReturnsOnCall[i] = struct {
		result1 []*slsa.ControlResult
		result2 error
	}{result1, result2}
}

func (fake *FakeVerifierImplementation) SelectBuildTypeControls(arg1 *slsa.VerificationOptions, arg2 *controls.Catalog, arg3 attestation.Statement) []*controls.Control {
	fake.selectBuildTypeControlsMutex.Lock()
	ret, specificReturn := fake.selectBuildTypeControlsReturnsOnCall[len(fake.selectBuildTypeControlsArgsForCall)]
	fake.selectBuildTypeControlsArgsForCall = append(fake.selectBuildTypeControlsArgsForCall, struct {
		arg1 *slsa.VerificationOptions
		arg2 *controls.Catalog
		arg3 attestation.Statement
	}{arg1, arg2, arg3})
	stub := fake.SelectBuildTypeControlsStub
	fakeReturns := fake.selectBuildTypeControlsReturns
	fake.recordInvocation("SelectBuildTypeControls", []interface{}{arg1, arg2, arg3})
	fake.selectBuildTypeControlsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVerifierImplementation) SelectBuildTypeControlsCallCount() int {
	fake.selectBuildTypeControlsMutex.RLock()
	defer fake.selectBuildTypeControlsMutex.RUnlock()
	return len(fake.selectBuildTypeControlsArgsForCall)
}

func (fake *FakeVerifierImplementation) SelectBuildTypeControlsCalls(stub func(*slsa.VerificationOptions, *controls.Catalog, attestation.Statement) []*controls.Control) {
	fake.selectBuildTypeControlsMutex.Lock()
	defer fake.selectBuildTypeControlsMutex.Unlock()
	fake.SelectBuildTypeControlsStub = stub
}

func (fake *FakeVerifierImplementation) SelectBuildTypeControlsArgsForCall(i int) (*slsa.VerificationOptions, *controls.Catalog, attestation.Statement) {
	fake.selectBuildTypeControlsMutex.RLock()
	defer fake.selectBuildTypeControlsMutex.RUnlock()
	argsForCall := fake.selectBuildTypeControlsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVerifierImplementation) SelectBuildTypeControlsReturns(result1 []*controls.Control) {
	fake.selectBuildTypeControlsMutex.Lock()
	defer fake.selectBuildTypeControlsMutex.Unlock()
	fake.SelectBuildTypeControlsStub = nil
	fake.selectBuildTypeControlsReturns = struct {
		result1 []*controls.Control
	}{result1}
}

func (fake *FakeVerifierImplementation) SelectBuildTypeControlsReturnsOnCall(i int, result1 []*controls.Control) {
	fake.selectBuildTypeControlsMutex.Lock()
	defer fake.selectBuildTypeControlsMutex.Unlock()
	fake.SelectBuildTypeControlsStub = nil
	if fake.selectBuildTypeControlsReturnsOnCall == nil {
		fake.selectBuildTypeControlsReturnsOnCall = make(map[int]struct {
			result1 []*controls.Control
		})
	}
	fake.selectBuildTypeControlsReturnsOnCall[i] = struct {
		result1 []*controls.Control
	}{result1}
}

func (fake *FakeVerifierImplementation) SelectCoreControls(arg1 *slsa.VerificationOptions, arg2 *controls.Catalog, arg3 controls.Category) []*controls.Control {
	fake.selectCoreControlsMutex.Lock()
	ret, specificReturn := fake.selectCoreControlsReturnsOnCall[len(fake.selectCoreControlsArgsForCall)]
	fake.selectCoreControlsArgsForCall = append(fake.selectCoreControlsArgsForCall, struct {
		arg1 *slsa.VerificationOptions
		arg2 *controls.Catalog
		arg3 controls.Category
	}{arg1, arg2, arg3})
	stub := fake.SelectCoreControlsStub
	fakeReturns := fake.selectCoreControlsReturns
	fake.recordInvocation("SelectCoreControls", []interface{}{arg1, arg2, arg3})
	fake.selectCoreControlsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVerifierImplementation) SelectCoreControlsCallCount() int {
	fake.selectCoreControlsMutex.RLock()
	defer fake.selectCoreControlsMutex.RUnlock()
	return len(fake.selectCoreControlsArgsForCall)
}

func (fake *FakeVerifierImplementation) SelectCoreControlsCalls(stub func(*slsa.VerificationOptions, *controls.Catalog, controls.Category) []*controls.Control) {
	fake.selectCoreControlsMutex.Lock()
	defer fake.selectCoreControlsMutex.Unlock()
	fake.SelectCoreControlsStub = stub
}

func (fake *FakeVerifierImplementation) SelectCoreControlsArgsForCall(i int) (*slsa.VerificationOptions, *controls.Catalog, controls.Category) {
	fake.selectCoreControlsMutex.RLock()
	defer fake.selectCoreControlsMutex.RUnlock()
	argsForCall := fake.selectCoreControlsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVerifierImplementation) SelectCoreControlsReturns(result1 []*controls.Control) {
	fake.selectCoreControlsMutex.Lock()
	defer fake.selectCoreControlsMutex.Unlock()
	fake.SelectCoreControlsStub = nil
	fake.selectCoreControlsReturns = struct {
		result1 []*controls.Control
	}{result1}
}

func (fake *FakeVerifierImplementation) SelectCoreControlsReturnsOnCall(i int, result1 []*controls.Control) {
	fake.selectCoreControlsMutex.Lock()
	defer fake.selectCoreControlsMutex.Unlock()
	fake.SelectCoreControlsStub = nil
	if fake.selectCoreControlsReturnsOnCall == nil {
		fake.selectCoreControlsReturnsOnCall = make(map[int]struct {
			result1 []*controls.Control
		})
	}
	fake.selectCoreControlsReturnsOnCall[i] = struct {
		result1 []*controls.Control
	}{result1}
}

func (fake *FakeVerifierImplementation) SelectUserControls(arg1 *slsa.VerificationOptions) []*controls.Control {
	fake.selectUserControlsMutex.Lock()
	ret, specificReturn := fake.selectUserControlsReturnsOnCall[len(fake.selectUserControlsArgsForCall)]
	fake.selectUserControlsArgsForCall = append(fake.selectUserControlsArgsForCall, struct {
		arg1 *slsa.VerificationOptions
	}{arg1})
	stub := fake.SelectUserControlsStub
	fakeReturns := fake.selectUserControlsReturns
	fake.recordInvocation("SelectUserControls", []interface{}{arg1})
	fake.selectUserControlsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVerifierImplementation) SelectUserControlsCallCount() int {
	fake.selectUserControlsMutex.RLock()
	defer fake.selectUserControlsMutex.RUnlock()
	return len(fake.selectUserControlsArgsForCall)
}

func (fake *FakeVerifierImplementation) SelectUserControlsCalls(stub func(*slsa.VerificationOptions) []*controls.Control) {
	fake.selectUserControlsMutex.Lock()
	defer fake.selectUserControlsMutex.Unlock()
	fake.SelectUserControlsStub = stub
}

func (fake *FakeVerifierImplementation) SelectUserControlsArgsForCall(i int) *slsa.VerificationOptions {
	fake.selectUserControlsMutex.RLock()
	defer fake.selectUserControlsMutex.RUnlock()
	argsForCall := fake.selectUserControlsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeVerifierImplementation) SelectUserControlsReturns(result1 []*controls.Control) {
	fake.selectUserControlsMutex.Lock()
	defer fake.selectUserControlsMutex.Unlock()
	fake.SelectUserControlsStub = nil
	fake.selectUserControlsReturns = struct {
		result1 []*controls.Control
	}{result1}
}

func (fake *FakeVerifierImplementation) SelectUserControlsReturnsOnCall(i int, result1 []*controls.Control) {
	fake.selectUserControlsMutex.Lock()
	defer fake.selectUserControlsMutex.Unlock()
	fake.SelectUserControlsStub = nil
	if fake.selectUserControlsReturnsOnCall == nil {
		fake.selectUserControlsReturnsOnCall = make(map[int]struct {
			result1 []*controls.Control
		})
	}
	fake.selectUserControlsReturnsOnCall[i] = struct {
		result1 []*controls.Control
	}{result1}
}

func (fake *FakeVerifierImplementation) VerifySignatures(arg1 context.Context, arg2 *slsa.VerificationOptions, arg3 attestation.Statement) error {
	fake.verifySignaturesMutex.Lock()
	ret, specificReturn := fake.verifySignaturesReturnsOnCall[len(fake.verifySignaturesArgsForCall)]
	fake.verifySignaturesArgsForCall = append(fake.verifySignaturesArgsForCall, struct {
		arg1 context.Context
		arg2 *slsa.VerificationOptions
		arg3 attestation.Statement
	}{arg1, arg2, arg3})
	stub := fake.VerifySignaturesStub
	fakeReturns := fake.verifySignaturesReturns
	fake.recordInvocation("VerifySignatures", []interface{}{arg1, arg2, arg3})
	fake.verifySignaturesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVerifierImplementation) VerifySignaturesCallCount() int {
	fake.verifySignaturesMutex.RLock()
	defer fake.verifySignaturesMutex.RUnlock()
	return len(fake.verifySignaturesArgsForCall)
}

func (fake *FakeVerifierImplementation) VerifySignaturesCalls(stub func(context.Context, *slsa.VerificationOptions, attestation.Statement) error) {
	fake.verifySignaturesMutex.Lock()
	defer fake.verifySignaturesMutex.Unlock()
	fake.VerifySignaturesStub = stub
}

func (fake *FakeVerifierImplementation) VerifySignaturesArgsForCall(i int) (context.Context, *slsa.VerificationOptions, attestation.Statement) {
	fake.verifySignaturesMutex.RLock()
	defer fake.verifySignaturesMutex.RUnlock()
	argsForCall := fake.verifySignaturesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVerifierImplementation) VerifySignaturesReturns(result1 error) {
	fake.verifySignaturesMutex.Lock()
	defer fake.verifySignaturesMutex.Unlock()
	fake.VerifySignaturesStub = nil
	fake.verifySignaturesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVerifierImplementation) VerifySignaturesReturnsOnCall(i int, result1 error) {
	fake.verifySignaturesMutex.Lock()
	defer fake.verifySignaturesMutex.Unlock()
	fake.VerifySignaturesStub = nil
	if fake.verifySignaturesReturnsOnCall == nil {
		fake.verifySignaturesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifySignaturesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVerifierImplementation) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVerifierImplementation) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ slsa.VerifierImplementation = new(FakeVerifierImplementation)
